export default {
  products: [
    {
      id: 1,
      name: 'Free Size Shirt',
      slug:'free_size_shirt_1',
      category: 'Shirt',
      image: '/images/download.jpeg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      id: 2,
      name: 'Fit Size Shirt',
      slug:'fit_size_shirt_2',

      category: 'Shirt',
      image: '/images/download_1.jpeg',
      price: 40,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      id: 3,
      name: 'Small Size Shirt',
      slug:'small_size_shirt_3',

      category: 'Shirt',
      image: '/images/images.jpeg',
      price: 90,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 19,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      id: 4,
      name: 'Small Size Shirt',
      slug:'small_size_shirt_4',

      category: 'Shirt',
      image: '/images/images_1.jpeg',
      price: 90,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 19,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      id: 5,
      name: 'Small Size Shirt',
      slug:'small_size_shirt_5',

      category: 'Shirt',
      image: '/images/images_2.jpeg',
      price: 90,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 19,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      id: 6,
      name: 'Small Size Shirt',
      slug:'small_size_shirt_6',

      category: 'Shirt',
      image: '/images/images_3.jpeg',
      price: 90,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 19,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      id: 7,
      name: 'Small Size Shirt',
      slug:'small_size_shirt_7',

      category: 'Shirt',
      image: '/images/images_4.jpeg',
      price: 90,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 19,
      countInStock: 20,
      description: 'A popular shirt',
    },
  ],
};
